core:
  dynatrace_tenant_address: abc12345.live.dynatrace.com
  deployment_environment: TEST
  log_level: WARN
  tag: ""
  procedure_timeout: 3600

  snowflake:
    account_name: "-"
    host_name: "-"

    database:
      name: "" # Default: DTAGENT_DB
      data_retention_time_in_days: 1

    warehouse:
      name: "" # Default: DTAGENT_WH

    resource_monitor:
      name: "" # Default: DTAGENT_RS, use "-" to skip
      credit_quota: 5

    roles:
      owner: "" # Default: DTAGENT_OWNER
      admin: "" # Default: DTAGENT_ADMIN, use "-" to skip
      viewer: "" # Default: DTAGENT_VIEWER
otel: {}
plugins:
  disabled_by_default: false
  deploy_disabled_plugins: true
  self_monitoring:
    send_bizevents_on_deploy: true
    send_bizevents_on_run: true
